# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1085, 673)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 50, 901, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.students = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.students.setAlternatingRowColors(True)
        self.students.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.students.setObjectName("students")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.students.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.students.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.students.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.students.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.students.addItem(item)
        self.gridLayout.addWidget(self.students, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.uczen = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.uczen.setObjectName("uczen")
        self.gridLayout.addWidget(self.uczen, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.failedstudents = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.failedstudents.setObjectName("failedstudents")
        self.gridLayout.addWidget(self.failedstudents, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.students.isSortingEnabled()
        self.students.setSortingEnabled(False)
        item = self.students.item(0)
        item.setText(_translate("Dialog", "Ali Hatbi"))
        item = self.students.item(1)
        item.setText(_translate("Dialog", "Jakub Hojol"))
        item = self.students.item(2)
        item.setText(_translate("Dialog", "Marcel Zmigrodzki"))
        item = self.students.item(3)
        item.setText(_translate("Dialog", "Mateusz \"root\" Maniak"))
        item = self.students.item(4)
        item.setText(_translate("Dialog", "Jakub Janczuk"))
        self.students.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Dialog", "Dodaj nowego ucznia"))
        self.label.setText(_translate("Dialog", "Wybierz ucznia ktory nie zda"))
        self.label_2.setText(_translate("Dialog", "Nie zdaja:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
